security:
  public-endpoints:
    - path: /api/user/register
    - path: /api/user/activate
    - path: /api/user/login
    - path: /api/refresh

    - path: /api/user
    - path: /api/certificate
    - path: /api/certificate/parent