services:
  postgres:
    image: postgres:latest
    container_name: Database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=pki
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
