CREATE TABLE accounts
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    status   VARCHAR(255)                            NOT NULL,
    user_id  BIGINT,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    issued_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE register_requests
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    verification_code VARCHAR(255)                            NOT NULL,
    expiration_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email             VARCHAR(255)                            NOT NULL,
    password          VARCHAR(255)                            NOT NULL,
    user_id           BIGINT,
    CONSTRAINT pk_register_requests PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name        VARCHAR(255)                            NOT NULL,
    last_name         VARCHAR(255)                            NOT NULL,
    organization_name VARCHAR(255)                            NOT NULL,
    role              SMALLINT                                NOT NULL,
    account_id        BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_email UNIQUE (email);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token UNIQUE (token);

ALTER TABLE register_requests
    ADD CONSTRAINT uc_register_requests_verificationcode UNIQUE (verification_code);

ALTER TABLE users
    ADD CONSTRAINT uc_users_account UNIQUE (account_id);

ALTER TABLE accounts
    ADD CONSTRAINT FK_ACCOUNTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE register_requests
    ADD CONSTRAINT FK_REGISTER_REQUESTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES accounts (id);